name: Test Workflow with Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/backend/requirements.txt
          pip install pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report=term-missing --cov-report=xml

      - name: Display coverage report
        run: |
          echo "Coverage report:"
          cat coverage.xml | head -n 50
